# Generated by Django 5.0.2 on 2025-03-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarlyAccessRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('specialization', models.CharField(max_length=100)),
                ('organization', models.CharField(blank=True, max_length=200, null=True)),
                ('want_early_access', models.BooleanField(default=True)),
                ('questions', models.TextField(blank=True, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-registration_date'],
            },
        ),
        migrations.DeleteModel(
            name='WebinarRegistration',
        ),
    ]
